[build]
publish = "public/"
command = "yarn build"
functions = "functions"

[build.environment]
HUGO_VERSION = "0.67.1"
TZ = "Europe/Berlin"

[[redirects]]
from = "/hebocon"
to = "https://bbb.kalk.space/b/kal-kpg-ink"
status = 302
